### ISSUE TITLE
Ошибка в исходном коде

### ISSUE THREAD

**Issue by kuzyara** [hal9000cc/RequestConsole9000#1]
https://github.com/hal9000cc/RequestConsole9000/blob/cba29b49b39fe93555a31abbabc1ed01fbd0e502/src/%D0%9A%D0%BE%D0%BD%D1%81%D0%BE%D0%BB%D1%8C%D0%97%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B29000/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L571

Недостаточное число параметров

**Comment by kuzyara** [comment]
И ещё, как вы относитесь с современным стандартам написания кода? 
В частности https://its.1c.ru/db/v8std#content:454:hdoc ?

**Comment by kuzyara** [comment]
Есть ли опыт работы с EDT?

**Comment by hal9000cc** [comment]
Ошибку вижу, спасибо!
Правда, не пойму, в каких условиях она воспроизводится...

> И ещё, как вы относитесь с современным стандартам написания кода?
К любым стандартам отношусь положительно, только я бы назвал это не "современный стандарт", а "рекомендуемые соглашения по написанию кода на платформе 1С".

> Есть ли опыт работы в EDT?
Нет, не знаком, но планирую попробовать.
