### ISSUE TITLE
Перевод разработки на EDT

### ISSUE THREAD

**Issue by kuzyara** [hal9000cc/RequestConsole9000#10]
Реквестирую сабж, там хоть половину тупых ошибок среда подсвечивает. 
И мне не нужно будет после релиза самостоятельно их заного править.

**Comment by kuzyara** [comment]
Вроде серверных вызовов при закрытии, отсутствующих параметров или несовместимости с тонким/веб-клиентом

**Comment by hal9000cc** [comment]
У меня пока нет платформы, совместимой с EDT...
Серверные вызовы при закрытии в разрабатываемой версии я уже убрал.

**Comment by kuzyara** [comment]
> Серверные вызовы при закрытии в разрабатываемой версии я уже убрал.

когда релиз?

**Comment by hal9000cc** [comment]
> когда релиз?
Точно сказать не могу, только из отпуска вернулся. Вряд ли ранее, чем через две недели.

**Comment by kuzyara** [comment]
> У меня пока нет платформы, совместимой с EDT

https://edt.1c.ru/docs/intro/requirements.php
> Общие требования к программному обеспечению
> Платформа «1С:Предприятие 8»
> Версии:
> от 8.3.8 до 8.3.14,
> 8.3.15 (не младше чем 8.3.15.1958),
> 8.3.16 (не младше чем 8.3.16.1502),
> 8.3.17 (не младше чем 8.3.17.1549).

@hal9000cc у тебя какая платформа?

**Comment by hal9000cc** [comment]
8.3.16.1224

**Comment by hal9000cc** [comment]
Перевел, пока только ветка dev.

**Comment by kuzyara** [comment]
свершилось!!!
