### ISSUE TITLE
Кнопка "В документ" не изменяет табличный документ

### ISSUE THREAD

**Issue by kuzyara** [hal9000cc/RequestConsole9000#11]
При нажатии кнопки "В документ" во второй и след. разы табличный документ не изменяется и не открывается новый, просто открывается старый. Даже на копии запроса. Это баг или фича??

**Comment by hal9000cc** [comment]
Скорее всего баг, буду разбираться.

**Comment by hal9000cc** [comment]
Исправлено в 1.1.9
