### ISSUE TITLE
Список планируемых фич

### ISSUE THREAD

**Issue by LevkinSergey** [hal9000cc/RequestConsole9000#13]
Есть ли где-нибудь в общем доступе планируемый список изменений в консоли? Я не нашел
И если нет, то планируется ли его выкладывать?

**Comment by kuzyara** [comment]
А что вы хотите изменить? Расширять функциональность?

**Comment by LevkinSergey** [comment]
у меня мысли больше по интеграции ее в универсальные инструменты. Если без них, то мысли такие

1. Интегрировать редактор кода с автокомплитом
1. В таблице просмотра сделать возможность в отдельной таблице просматривать свойства текущей строки. Как оказалось когда много колонок или они пустые очень удобная фича
1. Построение плана запроса. Но это вроде началось делаться
1. Сделать ее более легко интегрируемой 
1. Режим дерева запроса- возможность отдельно анализировать и разрабатывать каждый подзапрос

Думаю еще что-то появится по мере использования. Просто если что -то уже запланировано или уже в реализации, то можно и подождать реализации от автора

**Comment by LevkinSergey** [comment]
еще забыл, но это будет реализовываться в рамках универсальных инструментов- или интеграция с сервисом обмена кодом или свой сервис по обмену запросами и другими штуками. Ну и хранение в одном облаке с возможностью расшаривания запросов и т.п.
Возможно облако с авторизацией, возможно нет. еще не думал над этим

**Comment by kuzyara** [comment]
что за универсальные инструменты?

**Comment by LevkinSergey** [comment]
> что за универсальные инструменты?

https://github.com/cpr1c/tools_ui_1c

**Comment by kuzyara** [comment]
а так вы крафт1с...
сертификат истёк)

**Comment by LevkinSergey** [comment]
> а так вы крафт1с...
> сертификат истёк)

Какой сертификат?

**Comment by LevkinSergey** [comment]
Не вижу смысла делать что-то самому, если есть уже готовое и им могут поделиться

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/91268053-30a69680-e7a7-11ea-8fdd-3c3b936746f5.png)

**Comment by LevkinSergey** [comment]
это не я.
У меня только этот репозиторий и публикация на инфостарте. Все остальное - это копии

**Comment by LevkinSergey** [comment]
есть еще сайт to1c.ru. Но я до него никак не доберусь, чтобы его в человеческий вид привести

**Comment by kuzyara** [comment]
> 1. Интегрировать редактор кода с автокомплитом

Если вы про https://github.com/salexdv/bsl_console на монако - то это поломает совместимость, там же 8.3.14+

**Comment by LevkinSergey** [comment]
> Если вы про https://github.com/salexdv/bsl_console на монако - то это поломает совместимость, там же 8.3.14+ (вебкит с джаваскриптом я так понял)

Поломает, если не поставить проверку. Я бы для неподходящих платформ и ОС оставил как есть, а где можно там использовал эту консоль

**Comment by kuzyara** [comment]
Лучший код — этот тот код, который не написан. Он не упадёт, его не нужно покрывать тестами, не нужно рефакторить, и главное — он не потребляет ресурсов. 😎

Да и для плана запросов есть более удобные инструменты, тот же профайлер, sentryone plan explorer...

**Comment by LevkinSergey** [comment]
Про лучший код добавлю- он должен решать задачу. 
Про планы запросов- безусловно есть более удачные инструменты, но для их использования нужно еще что-то знать, нужно зайти в другую программу и там ее как то настроить, в разных ОС - это разные инструменты, ну и главное - это нужно еще куда-то идти и что-то делать, т.е. тратить время.

**Comment by kuzyara** [comment]
Вспоминая себя да, я тоже начинал изучать планы через галку получения плана запроса в консоли итс.
Ниже порог входа, проще обучение. 

Но у меня эта штука часто зависала/не работала, т.к. не понимая что в основе (лежит перезапись файла настроек! технологического журнала кластера серверов! читающегося по таймауту! с последующим парсингом всего! лога) - осознанно пользоваться инструментом не получится. 

И у меня (тогда) сложилось впечатление кривости! этого функционала в частности и смешанные чувства к инструменту в целом. А вы в курсе какое количество костыльного кода лежит под этой фичей?!

**Comment by kuzyara** [comment]
Так что Unix-Way наше всё: «Решайте одну задачу, но делайте это хорошо» 😎

**Comment by kuzyara** [comment]
Вон Евгений Люлюк постоянно напихивает новые фичи в свою консоль. Вроде бы крутые, и вроде бы даже работают. Но как только сценарий отходит от задуманного - всё это вылазит. По этому и перешёл на эту обработку.

**Comment by kuzyara** [comment]
> это нужно еще куда-то идти и что-то делать

Это и называется обучение.

**Comment by LevkinSergey** [comment]
анализ плана запросов не раскуривал. и лично пользовался за много лет всего пару раз. Поэтому ваши вопросы и аргументы понятны и я с ними согласен. 
Нужно найти золотую середину между функциональность, надежностью и скоростью работы. А это возможно сделать только в споре и обсуждениях

**Comment by LevkinSergey** [comment]
> > это нужно еще куда-то идти и что-то делать
> 
> Это и называется обучение. Лучше приложу гайд по нужному кейсу. И ликбез будет, и публикация, и реклама обработки. Брентозар кстати так делает.

Это будет круто.

**Comment by hal9000cc** [comment]
Списка планируемых фич, как такового нет. В ближайших планах добить анализ плана запросов и убрать все известные баги (работа под веб, и др.). Получить максимально стабильную версию.

> Но у меня эта штука часто зависала/не работала, т.к. не понимая что в основе (лежит перезапись файла настроек! технологического журнала кластера серверов! читающегося по таймауту! с последующим парсингом всего! лога) - осознанно пользоваться инструментом не получится.

В типовой консоли в первых версиях была полная жуть. Там заменялись настройки ТЖ, и начинали логгироваться все запросы, без всякого фильтра! Естественно, при анализе были жуткие тормоза.
Особенно весело было запустить это на продуктиве, после чего прибегал админ с круглыми глазами и криком "не понимаю, что происходит, системный диск сейчас переполниться!")))
В новых версиях вроде бы стало лучше.

**Comment by LevkinSergey** [comment]
спасибо. Я тогда задачи из проекта https://github.com/cpr1c/tools_ui_1c касаемые консоли запросов вам заведу сюда.
