### ISSUE TITLE
Ошибка при интеграции консоли запросов в конфигурацию

### ISSUE THREAD

**Issue by Serg777** [hal9000cc/RequestConsole9000#15]
Добрый день!
У нас запрещено открытие внешних обработок. Если встраивать обработку в конфигурацию (создал расширение, убрал безопасный режим, добавил обработку из файла), то при открытии консоли запросов вылетает ошибка: не найдена переменная. Когда добавляешь реквизит, то другая ошибка. Помогите пожалуйста, встройте обработку в расширение.

**Comment by hal9000cc** [comment]
Добрый день!
А можно чуть больше подробностей, текст ошибки?

**Comment by Serg777** [comment]
Добрый день!
Версия обработки 1.1.8

При открытии обработки, только добавленной в расширение вылетает ошибка:
Ошибка инициализации модуля: Обработка.КонсольЗапросов9000.МодульОбъекта
по причине:
{Обработка.КонсольЗапросов9000.МодульОбъекта(21,22)}: Переменная не определена (ИспользуемоеИмяФайла)
	ИмяФайлаОбработки = <<?>>ИспользуемоеИмяФайла;

Я добавил реквизит типа Строка(250), иия реквизите "ИспользуемоеИмяФайла". При открытии обработки, форма открывается, но появляется ошибка:

Несоответствие типов (параметр номер '3')
{Обработка.КонсольЗапросов9000.Форма.Форма.Форма(57)}:	НачатьПомещениеФайла(Новый ОписаниеОповещения("ПоместитьОбработкуНаСерверПродолжение", ЭтаФорма), Адрес, Объект.ИмяФайлаОбработки, Ложь);
{Обработка.КонсольЗапросов9000.Форма.Форма.Форма(2213)}:	ПолучитьИмяФайлаОбработкиНаСервере();
{Обработка.КонсольЗапросов9000.Форма.Форма.Форма(2171)}:			ПриОткрытииЗавершение();
{(1)}:ПриОткрытииПродолжение(ДополнительныеПараметры);
{Обработка.КонсольЗапросов9000.Форма.Форма.Форма(2084)}:	Выполнить(ДополнительныеПараметры.Продолжение + "(ДополнительныеПараметры);");

по причине:
Несоответствие типов (параметр номер '3')

**Comment by hal9000cc** [comment]
Проблема понятна. Можно взять сейчас версию в dev, и сделать все тоже самое, добавив реквизит. Скорее всего запустится, и будет работать все, кроме перехвата запросов в отладчике.

Эта же версия (1.1.9) работает и как дополнительная обработка, сохраненная в базе, тоже без перехвата. Перехват не работает потому, что нет обработки в виде файла в обоих случаях. Но, скорее всего, он бы и так не работал, так как в отладчике делается открытие внешней обработки.

**Comment by hal9000cc** [comment]
При встраивание в расширение перехват сделать, конечно можно, просто вызывать надо в отладчике обработку из расширения.

**Comment by Serg777** [comment]
![image](https://user-images.githubusercontent.com/1086504/97680848-65391600-1aa8-11eb-87b2-922ea5278533.png)
1.1.9 - консоль запросов в расширении работает, спасибо огромное.
Но при выполнении алгоритма вылетает ошибка (см. приложенные скриншот).

**Comment by hal9000cc** [comment]
Последняя версия в ветке dev должна нормально работать в составе расширения и в конфигурации, без доработок. Достаточно встроить как есть.
Единственное, пока не все методы запуска обработки кодом работают, по сравнению с файлом.

**Comment by hal9000cc** [comment]
В 1.1.10 исправлено.
