### ISSUE TITLE
Обязательное сохранение при закрытии

### ISSUE THREAD

**Issue by kuzyara** [hal9000cc/RequestConsole9000#17]
Сценарий1:
Запускаю отладку из конфигуратора
Редактирую/выполняю запрос
Останавливаю сеанс из конфигуратора (обновляю страницу в браузере/рву сеанс с кластера)
Последний выполненный запрос сохранится, так как работает автосохранение при выполнении запроса.

Сценарий2:
После очередного апдейта ошибки в процедуре ПослеЗакрытия, закрыть обработку не представляется возможным, так как эксепшн блокирует обработчик закрытия.

Сценарий3:
Закрываю эску (за день накапливается несколько сеансов из разных баз/копий), и в каждой просит сохранить пакет запросов. Но мне это не нужно, т.к. я знаю что запрос сохранён при последнем выполнении. Если нужно не потерять запрос - сохраняю вручную, заранее.

Вопрос:
Можно ли отключить вопрос перед закрытием о изменённом пакете запросов? Они ведь и так восстановятся при открытии... Или там в попытку всё завернуть...

Чтобы при закрытии никаких диалоговых окон не возникало. вот.

**Comment by hal9000cc** [comment]
Автосохранение делается не в основной файл.

Идеология такая. Нет попыток додумать за пользователя. Если кнопка сохранения не нажата, значит, это не нужно, и файл запросов не меняется. А автосохранение - это лишь страховка от потери результата.

Поэтому запрос о сохранении нужен. Только пользователь может решить - нужно ли сохранять результат в файл, или не менять его.
