### ISSUE TITLE
Не работает в веб-клиенте

### ISSUE THREAD

**Issue by kuzyara** [hal9000cc/RequestConsole9000#9]
![image](https://user-images.githubusercontent.com/2604430/86991681-e3a43c00-c1c9-11ea-8dab-f49da071f202.png)

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/86991985-a12f2f00-c1ca-11ea-967b-0095bc283778.png)

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/86992985-0552f280-c1cd-11ea-86a5-ca3655750e69.png)

**Comment by kuzyara** [comment]
штош ты делаеш то...

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/86993169-8611ee80-c1cd-11ea-8f67-94eabe2f9dcb.png)
![image](https://user-images.githubusercontent.com/2604430/86993193-94600a80-c1cd-11ea-9246-21cdcfa14411.png)

**Comment by kuzyara** [comment]
Давай код ревью(тестирование) перед выпуском новой версии делать, а?

**Comment by hal9000cc** [comment]
А старая версия в вебе работала нормально?
Вижу две проблемы:
1. Сжались кнопки.
2. "Расширение для работы с файлами не подключено".

Последний скрин не пойму, предпоследний - скорее всего, следствие 2.
А на втором скрине какая проблема?

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/87404168-62491100-c5f0-11ea-8d26-65bc71d47959.png)

**Comment by kuzyara** [comment]
> А старая версия в вебе работала нормально?
> Вижу две проблемы:
> 
> 1. Сжались кнопки.
> 2. "Расширение для работы с файлами не подключено".
> 
> Последний скрин не пойму, предпоследний - скорее всего, следствие 2.
> А на втором скрине какая проблема?

скрин с ошибкой "отсутствует Выбрать" возникает когда нажимаю на плюс в дереве метаданных (показал стрелочкой)

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/93169046-d4f07d00-f756-11ea-9b40-38d0f6c342b6.png)
в том ком клиенте тоже

**Comment by hal9000cc** [comment]
Исправлено в 1.1.9

**Comment by kuzyara** [comment]
> Исправлено в 1.1.9

когда релиз?

**Comment by hal9000cc** [comment]
Планирую в эти выходные. Если не будет чего-то непредвиденного.

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/97828117-2651cd00-1d01-11eb-8923-cc471f3f25fd.png)
да ты издеваешься...

**Comment by hal9000cc** [comment]
Можно подробнее - релиз платформы, операционной системы, браузера, номер строки с ошибкой?

У меня все тесты прошли на двух операционках и двух браузерах.

**Comment by kuzyara** [comment]
{ВнешняяОбработка.КонсольЗапросов9000.Форма.Форма.Форма(1778)}:	ДокументЗапись.Записать(стрИмяФайла);
{ВнешняяОбработка.КонсольЗапросов9000.Форма.Форма.Форма(2496)}:		ПакетЗапросов_Сохранить(ИмяФайлаАвтосохраненияСостояния, Истина);
{ВнешняяОбработка.КонсольЗапросов9000.Форма.Форма.Форма(2515)}:		Закрыть();

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/97856126-d857bc00-1d36-11eb-9692-8b6359fa1965.png)

**Comment by kuzyara** [comment]
> Можно подробнее - релиз платформы, операционной системы, браузера, номер строки с ошибкой?
> 
> У меня все тесты прошли на двух операционках и двух браузерах.

обновись на последнюю платформу уже

**Comment by hal9000cc** [comment]
Этот метод у меня работает в веб-клиенте. Запись в современных системах всегда производится асинхронно.

Так какой все-таки релиз платформы?

**Comment by hal9000cc** [comment]
Ну да, в справке указано, что метод Записать() в веб-клиенте работает:
> Доступность:
> Тонкий клиент, веб-клиент, сервер, толстый клиент, внешнее соединение.

Очень странно, что у тебя он выдает ошибку.

**Comment by hal9000cc** [comment]
Воспроизвел. Это не проблема работы в веб-клиенте. Это ошибка возникает, если поставить свойство конфигурации "Режим использования синхронных вызовов расширений платформы и внешних компонент" в "не использовать".

**Comment by hal9000cc** [comment]
Исправил в 1.1.9.16

**Comment by kuzyara** [comment]
Пишет "Для работы консоли необходимо установить расширение для работы с файлами."
Запускает скачивание файла untitled
[image](https://user-images.githubusercontent.com/2604430/97946928-af7f0780-1dc6-11eb-92b8-03e1b0f9c280.png)
судя по содержимому это xmlник
![image](https://user-images.githubusercontent.com/2604430/97947024-fb31b100-1dc6-11eb-8a9b-165cef8a930d.png)
Обработку так и не открывает. Что мне делать с этим xml файлом?

**Comment by kuzyara** [comment]
в ослике то же самое
![image](https://user-images.githubusercontent.com/2604430/97947779-5795d000-1dc9-11eb-919f-ed8acd1153f9.png)

**Comment by kuzyara** [comment]
хотя расширение для работы с 1с установлено и работает
![image](https://user-images.githubusercontent.com/2604430/97948042-3c779000-1dca-11eb-8d45-09687766141c.png)

**Comment by kuzyara** [comment]
короче, твой код говно)
![image](https://user-images.githubusercontent.com/2604430/97950519-1524c100-1dd2-11eb-936a-679b0caf09c1.png)

**Comment by hal9000cc** [comment]
После установки консоль работает?

**Comment by kuzyara** [comment]
добавь НачатьУстановкуРасширенияРаботыСФайлами()

**Comment by hal9000cc** [comment]
Так после установки работает?

**Comment by kuzyara** [comment]
## Замечание 1
https://github.com/hal9000cc/RequestConsole9000/blob/2038537633efb0fe45759be658b99b937ca4e0e2/src/%D0%9A%D0%BE%D0%BD%D1%81%D0%BE%D0%BB%D1%8C%D0%97%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B29000/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L2511-L2517
Если закрыть форму, успеет ли отработать обработчик установки расширения? И надо ли закрывать, если расширение таки было установлено?

Можно вот так:
```bsl
&НаКлиенте
Процедура ПослеЗавершенияПодключенияРасширенияРаботыСФайлами(Подключено, ДополнительныеПараметры) Экспорт

	фПодключеноРасширениеДляРаботыСФайлами = Подключено;

	Если НЕ Подключено Тогда
		Оповещение = Новый ОписаниеОповещения("НачатьУстановкуРасширенияРаботыСФайламиЗавершение", ЭтотОбъект);
		НачатьУстановкуРасширенияРаботыСФайлами(Оповещение);
		//Закрыть(); 
		Возврат;
	КонецЕсли;

	ПриОткрытииПродолжение();
	
КонецПроцедуры

&НаКлиенте
Процедура НачатьУстановкуРасширенияРаботыСФайламиЗавершение(ДополнительныеПараметры) Экспорт
	
	Оповещение = Новый ОписаниеОповещения("ПроверкаУстановкиРасширенияРаботыСФайлами", ЭтотОбъект);
	НачатьПодключениеРасширенияРаботыСФайлами(Оповещение);

КонецПроцедуры

&НаКлиенте
Процедура ПроверкаУстановкиРасширенияРаботыСФайлами(Подключено, ДополнительныеПараметры) Экспорт
	Если НЕ Подключено Тогда
		ПоказатьПредупреждение( , "Для работы консоли необходимо установить расширение работы с файлами!", , Объект.Заголовок);
		Закрыть();
	Иначе
		ПриОткрытииПродолжение();
	КонецЕсли;

КонецПроцедуры
```
## Замечание 2
https://github.com/hal9000cc/RequestConsole9000/blob/2038537633efb0fe45759be658b99b937ca4e0e2/src/%D0%9A%D0%BE%D0%BD%D1%81%D0%BE%D0%BB%D1%8C%D0%97%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B29000/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L2467-L2496
Если не учитывать установлено ли расширение работы с файлами, то при отказе/сбое установки расширения сохранение при закрытии (методом Закрыть();) упадет с ошибкой и вызовет скачивание файла untitled.

Лучше проверять перед закрытием возможность работы с файлами, например вот так:
```bsl
&НаКлиенте
Процедура ПередЗакрытием(Отказ, ЗавершениеРаботы, ТекстПредупреждения, СтандартнаяОбработка)
	#Если ВебКлиент Тогда
		Если НЕ фПодключеноРасширениеДляРаботыСФайлами Тогда
			Возврат;
		КонецЕсли;
	#КонецЕсли
```

**Comment by hal9000cc** [comment]
1 - В момент начала установки форма не закрывается, там висит диалог. Хотя, наверное, все же закрывается, остается только диалог. Я прогнал один раз все на чистой системе, расширение поставилось, но файл untitled прилетел.

3 - Согласен, добавлю в следующую версию.

Вообще, расширение ставиться один раз, я вообще не хотел делать его установку. На мой взгляд, это не такой важный вопрос.

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/98635407-dfe31a80-235f-11eb-9dee-c31e1954167e.png)
{ВнешняяОбработка.КонсольЗапросов9000.Форма.ФормаТабличногоДокумента.Форма(157)}:		ОбластьЗаполнения.Примечание = Колонка.ТипЗначения;
{ВнешняяОбработка.КонсольЗапросов9000.Форма.ФормаТабличногоДокумента.Форма(242)}:	СформироватьДокумент(Параметры);
{ВнешняяОбработка.КонсольЗапросов9000.Форма.ФормаТабличногоДокумента.Форма(255)}:	ОбновитьДокументНаСервере(Параметры);
{ВнешняяОбработка.КонсольЗапросов9000.Форма.Форма.Форма(3998)}:	ФормаТабличногоДокумента = ОткрытьФорму("ВнешняяОбработка.КонсольЗапросов9000.Форма.ФормаТабличногоДокумента", ПараметрыОткрытия, ЭтаФорма, Ложь);

**Comment by kuzyara** [comment]
Ошибка при удалении поля
![image](https://user-images.githubusercontent.com/2604430/98635592-436d4800-2360-11eb-8de5-b5685a99f394.png)
{ВнешняяОбработка.QueryWizard.Форма.QueryWizard.Форма(8437)}:		Parent = CurrentItems.GetParent();
{ВнешняяОбработка.QueryWizard.Форма.QueryWizard.Форма(10660)}:	AvailableFieldsDelete(Undefined);

**Comment by hal9000cc** [comment]
Все известные ошибки, проявляющиеся в работе в веб-клиенте в последнем релизе исправлены.

**Comment by kuzyara** [comment]
опубликуй релиз тогда уж
![image](https://user-images.githubusercontent.com/2604430/109092980-219aa400-774a-11eb-96c4-667e4f4ad3d6.png)

**Comment by kuzyara** [comment]
у тебя есть телеграм? что-то скомпилить дев-ветку не получается...

**Comment by hal9000cc** [comment]
> у тебя есть телеграм? что-то скомпилить дев-ветку не получается...

Отправил в личку.
